/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppRoot {}
  interface TodoCount {}
  interface TodoList {}
}

declare global {


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLTodoCountElement extends Components.TodoCount, HTMLStencilElement {}
  var HTMLTodoCountElement: {
    prototype: HTMLTodoCountElement;
    new (): HTMLTodoCountElement;
  };

  interface HTMLTodoListElement extends Components.TodoList, HTMLStencilElement {}
  var HTMLTodoListElement: {
    prototype: HTMLTodoListElement;
    new (): HTMLTodoListElement;
  };
  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'todo-count': HTMLTodoCountElement;
    'todo-list': HTMLTodoListElement;
  }
}

declare namespace LocalJSX {
  interface AppRoot {}
  interface TodoCount {}
  interface TodoList {}

  interface IntrinsicElements {
    'app-root': AppRoot;
    'todo-count': TodoCount;
    'todo-list': TodoList;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'todo-count': LocalJSX.TodoCount & JSXBase.HTMLAttributes<HTMLTodoCountElement>;
      'todo-list': LocalJSX.TodoList & JSXBase.HTMLAttributes<HTMLTodoListElement>;
    }
  }
}


